name: 'aws-secrets-manager-actions2'
description: 'GitHub Actions for AWS Secrets Manager'
inputs:
  SECRET_NAME:
    description: 'Set secret name that you want to get.'
    required: true
  AWS_ACCESS_KEY_ID:
    description: 'Set Aws Access Key ID'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'Set Aws Secret access Key'
    required: true
  AWS_DEFAULT_REGION:
    description: 'Set Aws default region'
    required: true
  OUTPUT_PATH:
    description: 'Set output file where variables are write'
    required: false
  EXPORT_TO_ENV:
    description: 'Whether to export secrets to the environment (set to false and use OUTPUT_PATH if you only want to write to an .env file, for example)'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'lock'
  color: 'orange'
